[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [
    "staticlib",
    "cdylib",
    "rlib",
] # Allows multiple output formats for flexibility

[dependencies]
# Core dependencies
leptos = "0.7" # Main Leptos framework

# Optional dependencies for SSR and Axum-based server
tower-http = { version = "0.6", optional = true }
leptos_server = "0.7"
axum = { version = "0.7", optional = true }
leptos_axum = { version = "0.7", optional = true }
tower = { version = "0.5", optional = true }
[features]
# Hydration for client-side rendering
hydrate = ["leptos/hydrate"]

# Server-Side Rendering (SSR) setup
ssr = [
    "leptos/ssr",      # Enable SSR in Leptos
    "dep:leptos_axum", # Leptos integration with Axum
    "dep:axum",        # Axum web framework
    "dep:tower",       # Core Tower utilities
    "dep:tower-http",  # Tower HTTP utilities
]
